// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT BY HAND
// Generated by: scripts/generate-astro-collections.mjs
// Source of truth: src/sections.json

import { defineCollection, z } from "astro:content";

const entrySchema = z.object({
  title: z.string(),
  type: z.string(),
  summary: z.string(),
  tags: z.array(z.string().min(1)).min(1),
  status: z.enum(["public", "private"]),
  created: z.preprocess(
    (v) => (v instanceof Date ? v.toISOString().slice(0, 10) : v),
    z.string()
  ),
  updated: z.preprocess(
    (v) => (v instanceof Date ? v.toISOString().slice(0, 10) : v),
    z.string()
  ),
  image: z.string().optional(),
});

export const collections = {
  "characters": defineCollection({ schema: entrySchema }),
  "organizations": defineCollection({ schema: entrySchema }),
  "places": defineCollection({ schema: entrySchema }),
  "artifacts": defineCollection({ schema: entrySchema }),
  "redactory": defineCollection({ schema: entrySchema }),
  "sigillums": defineCollection({ schema: entrySchema }),
};
