// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT BY HAND
// Generated by: scripts/generate-astro-collections.mjs
// Source of truth: src/sections.json

import { defineCollection, z } from "astro:content";

const entrySchema = z.object({
  title: z.string(),
  type: z.string(),
  summary: z.string(),
  affiliation: z.string().optional(),
  age: z.union([z.string(), z.number()]).optional(),
  height: z.union([z.string(), z.number()]).optional(),
  designation: z.string().optional(),
  birth_year: z.union([z.string(), z.number()]).optional(),
  birthplace: z.string().optional(),
  rank: z.string().optional(),
  house: z.string().optional(),
  registry_status: z.string().optional(),
  build: z.string().optional(),
  complexion: z.string().optional(),
  hair: z.string().optional(),
  eyes: z.string().optional(),
  dress: z.string().optional(),
  residence: z.string().optional(),
  occupation: z.string().optional(),
  headquarters: z.string().optional(),
  founded: z.string().optional(),
  jurisdiction: z.string().optional(),
  status_label: z.string().optional(),
  sealing_status: z.string().optional(),
  custody: z.string().optional(),
  known_principle: z.string().optional(),
  domain: z.string().optional(),
  church_name: z.string().optional(),
  principle: z.string().optional(),
  keeper_name: z.string().optional(),
  user_status: z.string().optional(),
  priority: z.number().optional(),
  tags: z.array(z.string().min(1)).min(1),
  status: z.enum(["public", "private"]),
  created: z.preprocess(
    (v) => (v instanceof Date ? v.toISOString().slice(0, 10) : v),
    z.string()
  ),
  updated: z.preprocess(
    (v) => (v instanceof Date ? v.toISOString().slice(0, 10) : v),
    z.string()
  ),
  image: z.string().optional(),
});

export const collections = {
  "characters": defineCollection({ schema: entrySchema }),
  "organizations": defineCollection({ schema: entrySchema }),
  "sine": defineCollection({ schema: entrySchema }),
  "places": defineCollection({ schema: entrySchema }),
  "apparatus": defineCollection({ schema: entrySchema }),
  "systems": defineCollection({ schema: entrySchema }),
  "cosmology": defineCollection({ schema: entrySchema }),
};
